templates:
- buildContainer: polygonhell/nodejs-kt:latest
  pushCommand: npm i && npm run start
  deployContainer: someOtherURL
  name: TSCreateReactApp
  ports:
  - 3000
  sourceFiles:
  - src
  - public
  - package.json
  - package-lock.json
  - tsconfig.json
name: name
author: null
projects:
- name: main
  ports: []
  template: TSCreateReactApp
